(function($){var widgetCurrentContent=new Array();var widgets=new Array();var loadTotal=0;var loadCount=0;var widgetDefaultUrl='https://h9v3f5q9.ssl.hwcdn.net/';String.prototype.hashCode=function(){var hash=0;if(this.length==0)return hash;for(i=0;i<this.length;i++){char=this.charCodeAt(i);hash=((hash<<5)-hash)+char;hash=hash&hash;}
return hash;}
jQuery(document).on('change','.user-split-by',function(){jQuery('.widget-loader').show();var widgetObj=jQuery(this).closest('.sotic-widget-content');var key=jQuery(this).attr('name');var value=jQuery(this).val();var existingParams=atob(jQuery(widgetObj).attr('data-widget-params'));var newParams=btoa(existingParams+"&"+key+"="+value);jQuery(widgetObj).removeData('widget-params');jQuery(widgetObj).attr('data-widget-params',newParams);var settings=getWidgetSettings(widgetObj);loadWidget(settings);});jQuery(document).on('click','.reload-widget-with-data',function(){jQuery('.widget-loader').show();var dataKey=jQuery(this).data('widget-ctm-p-k');var dataVal=jQuery(this).data('widget-ctm-p-v');var widgetObj=jQuery(this).closest('.sotic-widget-content');jQuery(widgetObj).removeData('widget-params');jQuery(widgetObj).attr('data-widget-params',btoa(dataKey+'='+dataVal));var settings=getWidgetSettings(widgetObj);loadWidget(settings);});jQuery(document).on('click','[data-widgetbutton]',function(){jQuery('.widget-loader').show();if(jQuery(this).attr('data-widgetbuttonprevent')==null){if(jQuery(this).data('widgetbutton').indexOf(',')){var dataIDarray=jQuery(this).data('widgetbutton').split(',');jQuery.each(dataIDarray,function(i,d){var dataID='[id="'+d+'-content"]';var widgetObj=jQuery(dataID);console.dir(widgetObj)
jQuery(widgetObj).each(function(k,v){var settings=getWidgetSettings(v);loadWidget(settings);});});}else{var dataID='[id="'+jQuery(this).data('widgetbutton')+'-content"]';var widgetObj=jQuery(dataID);jQuery(widgetObj).each(function(k,v){var settings=getWidgetSettings(v);loadWidget(settings);});}
jQuery(this).attr('data-widgetbuttonprevent','true');}});function getWidgetSettings(widgetObj){$widgetObj=jQuery(widgetObj);var settings={widgetId:$widgetObj.attr('data-widget-id'),refresh:$widgetObj.attr('data-refresh-rate'),id:$widgetObj.attr('id'),url:$widgetObj.attr('data-widget-url'),params:$widgetObj.attr('data-widget-params'),lang:$widgetObj.attr('data-widget-lang')};settings.url=(typeof settings.url!='undefined'&&settings.url!="")?settings.url:widgetDefaultUrl;settings.params=(typeof settings.params!='undefined'&&settings.params!="")?settings.params:'';settings.lang=(typeof settings.lang!='undefined'&&settings.lang!="")?settings.lang:'en';return settings;}
function loadWidget(settings){var params=settings.params!=''?'?params='+settings.params:'';var widgetId=settings.widgetId.split('/')[1];millisecondTimeout=settings.refresh*1000;if(millisecondTimeout>0&&millisecondTimeout<30000){millisecondTimeout=30000;}
var widgetInfo=settings.widgetId.split("/");settings.project=widgetInfo[0];settings.adminId=widgetInfo[1];var widgetURL=settings.url+settings.project+"/"+settings.lang+"/"+settings.adminId+params;var theHash=(settings.params).hashCode().toString().replace('-','a');if(theHash==="0"){var theCallback='jsonp_widget_'+widgetId;}else{var theCallback='jsonp_widget_'+widgetId+'_'+theHash;}
jQuery.ajax({url:widgetURL,type:'GET',cache:true,dataType:'jsonp',jsonpCallback:theCallback,success:function(data){var content=data.content;if(content.length>0&&content!=widgetCurrentContent[settings.id]){widgetCurrentContent[settings.id]=content;jQuery('[data-widget-id="'+settings.widgetId+'"][data-widget-params="'+settings.params+'"]').html(content);}
jQuery('[data-widget-loader="'+settings.widgetId+'"] .widget-loader').hide();$(window).trigger('widget-load',{'widgetID':settings.widgetId});loadCount++;if(loadCount==loadTotal){$(window).trigger('widget-load-all');}}});if(millisecondTimeout>0){this.setTimeout(function(){loadWidget(settings)},millisecondTimeout);}}
$.fn.soticWidgets=function(){var widgetsLoaded=[];loadTotal=jQuery('.sotic-widget-content').length;jQuery('.sotic-widget-content').each(function(i,val){widgetId=jQuery(val).attr('data-widget-id');widgetHtml=jQuery(val).html();widgetParams=jQuery(val).attr('data-widget-params');if(widgetsLoaded.indexOf(widgetId+'&'+widgetParams)<0&&widgetHtml.trim()==''){if(jQuery(val).attr('data-widget-load')===''){widgetsLoaded.push(widgetId+'&'+widgetParams);var settings=getWidgetSettings(val);loadWidget(settings);}}else{jQuery('[data-widget-loader="'+widgetId+'"] .widget-loader').hide();loadCount++;}});};}(jQuery));jQuery.cachedScript=function(url,options){options=jQuery.extend(options||{},{dataType:"script",cache:true,url:url});return jQuery.ajax(options);};jQuery(function(){jQuery(document).soticWidgets();});